### ISSUE TITLE
User can generate random Chuck Norris jokes or based on category

### ISSUE THREAD

**Issue by khanhnguyenq** [khanhnguyenq/ajax-project#1]
## ⚙️ Feature

User can generate random Chuck Norris jokes or based on category

## 📐 Functionality

Create a responsive landing page that allows the user to generate a joke based on a category or a random joke

## 🖼️ Wireframes

<img width="304" alt="Screenshot 2023-11-26 at 15 51 32" src="https://github.com/khanhnguyenq/ajax-project/assets/114459075/200e1e6f-86c4-475f-be40-a6568f891e94">
<img width="909" alt="Screenshot 2023-11-26 at 15 50 08" src="https://github.com/khanhnguyenq/ajax-project/assets/114459075/b9617c0d-2d09-4200-bdc3-32c3b10e4ee8">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML elements in header to match the figma
- [x] Below header, create HTML elements to switch between pages
  - [x] Add `'click'` event listeners to show and hide navbar
- [x] Add `'button'` elements to the landing page that will generate a joke based on the user selection
- [x] Complete landing page using the appropriate layout classes
  - [x] Write CSS for mobile first
  - [x] Adjust stylings to fluidly adapt to desktop
- [x] Add a `'click'` event listener to the category container that will:
  - [x] prevent the page from refreshing
  - [x] get the `textContent` of the button
  - [x] add the `textContent` to the API search request
  - [x] store the returned data in a new object
  - [x] assigns an `entryId` property to the new object, taken from the `nextEntryId` property of the data model
  - [x] increments the `nextEntryId` property of the data model so that if another entry is generated later, it will receive a different `entryId`.
  - [x] adds the new object to the beginning of the data model's array of entries.
- [x] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x]  Test the app by generating some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` before each page reload.
  - [x] each new generated object is receiving an incrementing entryId property.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
