### ISSUE TITLE
User can view all previously generate jokes

### ISSUE THREAD

**Issue by khanhnguyenq** [khanhnguyenq/ajax-project#2]
## ⚙️ Feature

User can view their generated jokes and previously generated jokes

## 📐 Functionality

Display generated joke in a different page and all generated jokes are saved in another page for viewing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-11-28 at 11 43 16](https://github.com/khanhnguyenq/ajax-project/assets/114459075/6c4b5f40-e1bf-4f0b-a61b-d0733096c460)
![Screenshot 2023-11-28 at 11 43 42](https://github.com/khanhnguyenq/ajax-project/assets/114459075/709fd122-ace1-45cd-aedd-fdb812f2fdc5)
![Screenshot 2023-11-28 at 11 44 37](https://github.com/khanhnguyenq/ajax-project/assets/114459075/0964b538-6d17-4690-92a9-cb5d8de2489a)
![Screenshot 2023-11-28 at 11 44 52](https://github.com/khanhnguyenq/ajax-project/assets/114459075/6d7719e7-ee39-4d5b-9c67-2ce9445bcb78)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML elements for "Joke" page so it matches the figma
  - [x] Write CSS for mobile first
  - [x] Adjust styling to adapt to desktop
- [x]  Create HTML elements for "Saved" page
  - [x] Write CSS for mobile first
  - [x] Adjust styling to adapt to desktop
- [x] For the pages above, create a navbar to return to the home page
- [x] In "Joke" page:
  - [x] create a container to display the generate joke
    - [x] add an empty unordered list to the container element
    - [x] create a dummy joke to the unordered list in the HTML
  - [x] create a button to generate another joke in the same category
- [x] In "Saved" page:
  - [x] create a container to display all generated jokes
    - [x] add an empty unordered list to the container element
    - [x] create a dummy joke to the unordered list in the HTML
- [x] Define a function named `renderJoke` with a single parameter named `joke`. This parameter represents a single object for a single joke from the `data.joke` array. The function should generate and return a DOM tree for a single joke that matches the dummy joke you created in the unordered list.
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.joke` array and generate a DOM tree for each joke in the array, and append that DOM tree to the unordered list on the "Saved" page.
- [x] Remove the example HTML joke from `index.html` once the user's joke are successfully appended to the DOM in both "Joke" and "Saved".
- [x] Create a new function named `viewSwap` with a single parameter representing the view to show(`"landing"`, `"saved"`, or `"joke"`). This function should show the view whose name was provided as an argument, as well as assign the string argument to the `data.view` property so that the currently shown view is tracked in the data model for the application.
- [x] Update the `click` callback for the category event listener to:
  - [x] Render a DOM for the generated joke
  - [x] Add the DOM tree into the "Joke" page
  - [x] use the `viewSwap` to show the "Joke" page
- [x]  Update the `DOMContentLoaded` callback function to:
  - [x] uses `viewSwap` function to show the view which was displayed prior to the page refresh
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
