### ISSUE TITLE
User can update and save jokes

### ISSUE THREAD

**Issue by khanhnguyenq** [khanhnguyenq/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate another joke from the same category on the same page. Also user can favorite a joke once its generated or from the saved page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to generate another joke by clicking on a button and save a joke by clicking on the heart icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2023-11-30 at 10 08 17](https://github.com/khanhnguyenq/ajax-project/assets/114459075/06f6a5f2-17ad-4229-82ac-fa4fe49220c6)
![Screenshot 2023-11-30 at 10 08 33](https://github.com/khanhnguyenq/ajax-project/assets/114459075/6cf23ebf-4079-42b0-a639-c6a156bfcf8d)
![Screenshot 2023-11-30 at 10 09 01](https://github.com/khanhnguyenq/ajax-project/assets/114459075/b4a554a5-db05-4376-bf6c-0573eec43fb2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update landing page to include link to favorite tab
- [x] Create HTML elements for favorite tab
  - [x] Write CSS for mobile first and ensure adaptability to desktop
- [x] Add a `click` event listener to the `"Generate me another!"` button that will:
  - [x] create a new `XMLHttpRequest`
  - [x] get the `API` for another joke in the same category
  - [x] replaces the current displayed joke with the newly generated joke
- [x] Update `data` object in `data.js` to include a `favorite` array.  
- [x] Add  `favorite` icon to all off the generated joke
- [x] Add a `click` event for the `favorite` icon that will:
  - [x] obtain the `joke` object and `prepend` it to the `favorite` array in `data.js`
- [x] update `DOMContentLoaded` event to:
  - [x] Loop through the `favorite` array, generate a DOM tree for each object, and `prepend` the DOM tree into the `"favorite"` tab 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
